name: yubidart
description: Yubico Services for Dart and Flutter.
homepage: https://github.com/reddwarf03/yubidart

version: 2.0.0-dev.1

environment:
  sdk: '>=2.18.4 <3.0.0'

dependencies:

  # Implementations of SHA, MD5, and HMAC cryptographic functions
  crypto: ^3.0.2
  cryptography: ^2.0.5

  flutter:
    sdk: flutter

  # A composable, multi-platform, Future-based API for HTTP requests
  http: ^0.13.5

  # Flutter plugin for accessing the NFC features on Android and iOS.
  nfc_manager: ^3.1.1

  # Nonce contains a static generator that generates random alphanumeric strings, and can be constructed as an object containing a generated string
  nonce: ^1.2.0

  pem: ^2.0.1

  plugin_platform_interface: ^2.0.2
  # pointycastle: ^3.6.2

dev_dependencies:
  flutter_lints: ^2.0.1
  flutter_test:
    sdk: flutter
  # Automatically organize your dart imports
  import_sorter: ^4.6.0
  test: ^1.21.4

flutter:
  plugin:
    platforms:
      ios:
        pluginClass: YubikitIosPlugin
        dartPluginClass: YubidartIos
      android:
        package: net.archethic.yubikit_android
        pluginClass: YubikitAndroidPlugin
        dartPluginClass: YubidartAndroid
